name: herbgo
description: "An AI powered herb encyclopedia app that helps you learn about herbs, their benefits, and how to use them in your daily life. It also includes a feature to generate herb-based recipes."

publish_to: 'none'

version: 3.1.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  google_generative_ai: ^0.2.2
  path_provider: ^2.1.1
  camera: ^0.10.5+9
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo.png"
  